// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6qcTjoqdEQCNPrGTZ6NPaQbTbGXtIo04',
    appId: '1:771042533519:web:5c6fe77295a5cfa6dbd0fa',
    messagingSenderId: '771042533519',
    projectId: 'tourism-app-a4819',
    authDomain: 'tourism-app-a4819.firebaseapp.com',
    storageBucket: 'tourism-app-a4819.firebasestorage.app',
    measurementId: 'G-THCHQWMLHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz2BlBX7w8tIkKBo47tvbb_PH6QQAsBOI',
    appId: '1:771042533519:android:3716668acb4bfb89dbd0fa',
    messagingSenderId: '771042533519',
    projectId: 'tourism-app-a4819',
    storageBucket: 'tourism-app-a4819.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbbfJiewqMMYVTNRI4PDiFjfXp_uB_5Tg',
    appId: '1:771042533519:ios:8ca07675ed4254d9dbd0fa',
    messagingSenderId: '771042533519',
    projectId: 'tourism-app-a4819',
    storageBucket: 'tourism-app-a4819.firebasestorage.app',
    iosBundleId: 'com.example.tourismApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbbfJiewqMMYVTNRI4PDiFjfXp_uB_5Tg',
    appId: '1:771042533519:ios:8ca07675ed4254d9dbd0fa',
    messagingSenderId: '771042533519',
    projectId: 'tourism-app-a4819',
    storageBucket: 'tourism-app-a4819.firebasestorage.app',
    iosBundleId: 'com.example.tourismApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6qcTjoqdEQCNPrGTZ6NPaQbTbGXtIo04',
    appId: '1:771042533519:web:a6eeff97e256e02fdbd0fa',
    messagingSenderId: '771042533519',
    projectId: 'tourism-app-a4819',
    authDomain: 'tourism-app-a4819.firebaseapp.com',
    storageBucket: 'tourism-app-a4819.firebasestorage.app',
    measurementId: 'G-6HTZHR5LST',
  );
}
