import 'dart:typed_data';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

Future<void> downloadReservationPdf({
  required Map<String, dynamic> data,
  required String trackingCode,
}) async {
  final bytes = await _buildReservationPdf(
    data: data,
    trackingCode: trackingCode,
  );

  await Printing.sharePdf(
    bytes: bytes,
    filename: 'smart_travel_$trackingCode.pdf',
  );
}

Future<Uint8List> _buildReservationPdf({
  required Map<String, dynamic> data,
  required String trackingCode,
}) async {
  final document = pw.Document();
  final targetType = _plainText(data['targetType']).toUpperCase();
  final title = _plainText(data['title']);
  final rows = _reservationRows(data, trackingCode);
  final transportTickets = _transportTickets(data);

  document.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(32),
      build:
          (context) => [
            pw.Container(
              padding: const pw.EdgeInsets.all(18),
              decoration: pw.BoxDecoration(
                color: PdfColor.fromHex('#E9F7F7'),
                borderRadius: pw.BorderRadius.circular(12),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    'Smart Travel',
                    style: pw.TextStyle(
                      fontSize: 24,
                      fontWeight: pw.FontWeight.bold,
                      color: PdfColor.fromHex('#176B6B'),
                    ),
                  ),
                  pw.SizedBox(height: 6),
                  pw.Text(
                    'Booking Confirmation',
                    style: pw.TextStyle(
                      fontSize: 16,
                      color: PdfColor.fromHex('#223333'),
                    ),
                  ),
                ],
              ),
            ),
            pw.SizedBox(height: 18),
            pw.Text(
              title.isEmpty ? 'Booked Item' : title,
              style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 6),
            pw.Text(
              targetType,
              style: pw.TextStyle(
                fontSize: 12,
                fontWeight: pw.FontWeight.bold,
                color: PdfColor.fromHex('#176B6B'),
              ),
            ),
            pw.SizedBox(height: 16),
            pw.Container(
              padding: const pw.EdgeInsets.symmetric(
                horizontal: 14,
                vertical: 10,
              ),
              decoration: pw.BoxDecoration(
                color: PdfColor.fromHex('#FFF1B8'),
                borderRadius: pw.BorderRadius.circular(10),
                border: pw.Border.all(color: PdfColor.fromHex('#E0A800')),
              ),
              child: pw.Text(
                'Tracking Code: $trackingCode',
                style: pw.TextStyle(
                  fontSize: 15,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColor.fromHex('#6B4700'),
                ),
              ),
            ),
            pw.SizedBox(height: 18),
            _detailsTable(rows),
            if (transportTickets.isNotEmpty) ...[
              pw.SizedBox(height: 20),
              pw.Text(
                'Transport Tickets',
                style: pw.TextStyle(
                  fontSize: 16,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 8),
              _transportTicketsTable(transportTickets),
            ],
            pw.SizedBox(height: 24),
            pw.Divider(color: PdfColors.grey400),
            pw.Text(
              'This document was generated by Smart Travel.',
              style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
            ),
          ],
    ),
  );

  return document.save();
}

pw.Widget _detailsTable(List<List<String>> rows) {
  return pw.Table.fromTextArray(
    headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
    headerDecoration: pw.BoxDecoration(color: PdfColor.fromHex('#F0F5F5')),
    cellAlignment: pw.Alignment.centerLeft,
    cellPadding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 7),
    columnWidths: const {
      0: pw.FlexColumnWidth(1.25),
      1: pw.FlexColumnWidth(2.75),
    },
    headers: const ['Field', 'Value'],
    data: rows,
  );
}

pw.Widget _transportTicketsTable(List<Map<String, dynamic>> tickets) {
  return pw.Table.fromTextArray(
    headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
    headerDecoration: pw.BoxDecoration(color: PdfColor.fromHex('#F0F5F5')),
    cellAlignment: pw.Alignment.centerLeft,
    cellPadding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 7),
    headers: const ['Type', 'Route', 'Date', 'Number', 'Price'],
    data:
        tickets.map((ticket) {
          final mode = _plainText(ticket['mode']).toUpperCase();
          final route = [
            _cityText(ticket['from']),
            _cityText(ticket['to']),
          ].where((value) => value.isNotEmpty).join(' -> ');
          final number =
              _plainText(ticket['flightNumber']).isNotEmpty
                  ? _plainText(ticket['flightNumber'])
                  : _plainText(ticket['trainNumber']);

          return [
            mode,
            route,
            _dateText(ticket['departAt'] ?? ticket['date']),
            number,
            _priceText(ticket['basePrice'] ?? ticket['price']),
          ];
        }).toList(),
  );
}

List<List<String>> _reservationRows(
  Map<String, dynamic> data,
  String trackingCode,
) {
  final rows = <List<String>>[
    ['Tracking Code', trackingCode],
    ['Status', _plainText(data['bookingStatus']).toUpperCase()],
    ['Item Type', _plainText(data['targetType']).toUpperCase()],
    ['Total Price', _plainText(data['totalPrice'] ?? data['price'])],
  ];

  _addIfNotEmpty(rows, 'Name', data['name']);
  _addIfNotEmpty(rows, 'Surname', data['surname']);
  _addIfNotEmpty(rows, 'Origin', data['origin']);
  _addIfNotEmpty(rows, 'Destination', data['destination']);
  _addIfNotEmpty(rows, 'Trip Type', data['tripType']);
  _addIfNotEmpty(rows, 'Passengers', data['passengerCount']);
  _addIfNotEmpty(rows, 'Room', data['roomLabel']);
  _addIfNotEmpty(rows, 'Stay Start', _dateText(data['stayStartDate']));
  _addIfNotEmpty(rows, 'Stay End', _dateText(data['stayEndDate']));
  _addIfNotEmpty(rows, 'Return Date', _dateText(data['returnDate']));
  _addIfNotEmpty(rows, 'Booked At', _dateText(data['bookedAt']));
  _addIfNotEmpty(rows, 'Reservation Created', _dateText(data['createdAt']));

  return rows;
}

void _addIfNotEmpty(List<List<String>> rows, String label, Object? value) {
  final text = _plainText(value);
  if (text.isEmpty) return;
  rows.add([label, text]);
}

List<Map<String, dynamic>> _transportTickets(Map<String, dynamic> data) {
  final tickets = data['transportTickets'];
  if (tickets is! List) return const [];
  return tickets
      .whereType<Map>()
      .map((ticket) => Map<String, dynamic>.from(ticket))
      .toList();
}

String _cityText(Object? value) {
  if (value is Map) {
    return _plainText(value['city'] ?? value['name']);
  }
  return _plainText(value);
}

String _priceText(Object? value) {
  final text = _plainText(value);
  if (text.isEmpty) return '';
  if (text.startsWith(r'$')) return text;
  return '\$$text';
}

String _dateText(Object? value) {
  if (value == null) return '';
  if (value is Timestamp) return _formatDateTime(value.toDate());
  if (value is DateTime) return _formatDateTime(value);
  return _plainText(value);
}

String _formatDateTime(DateTime date) {
  final day = date.day.toString().padLeft(2, '0');
  final month = date.month.toString().padLeft(2, '0');
  final year = date.year.toString();
  final hour = date.hour.toString().padLeft(2, '0');
  final minute = date.minute.toString().padLeft(2, '0');
  return '$day/$month/$year $hour:$minute';
}

String _plainText(Object? value) {
  if (value == null) return '';
  if (value is Timestamp) return _dateText(value);
  return value.toString().trim();
}
